language: python
python:
    - 2.6
    - 2.7
addons:
  postgresql: "9.3"

env:
    - DB=postgresql
      CONFIG_TYPE=py
    - DB=mysql
      CONFIG_TYPE=py
    - DB=postgresql
      CONFIG_TYPE=yaml
    - DB=mysql
      CONFIG_TYPE=yaml

install:
    - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then travis_retry pip install importlib; fi
    - if [[ $DB == "postgresql"]]; then travis_retry pip install psycopg2; fi
    - if [[ $DB == "mysql" ]]; then travis_retry pip install MySQL-python; fi
    - if [[ $CONFIG_TYPE == "yaml"]]; then pip install PyYAML==3.11; fi
    - pip install -r requirements.txt
    - pip install coveralls

before_script:
    - if [[ $DB == "postgresql" && $CONFIG_TYPE == "yaml" ]]; then psql -c "create database rsm_test;" -U postgres; cp tests/postgresql.yaml rsm.yaml; fi
    - if [[ $DB == "mysql" && $CONFIG_TYPE == "yaml" ]]; then mysql -e "create database rsm_test;" -uroot; cp tests/mysql.yaml rsm.yaml; fi
    - if [[ $DB == "postgresql" && $CONFIG_TYPE == "py" ]]; then psql -c "create database rsm_test;" -U postgres; cp tests/rsm_postgresql.py rsm.py; fi
    - if [[ $DB == "mysql" && $CONFIG_TYPE == "py" ]]; then mysql -e "create database rsm_test;" -uroot; cp tests/rsm_mysql.py rsm.py; fi

script:
    nosetests --with-coverage --cover-package=raw_sql_migrate

after_success:
    - coveralls
    - rm rsm.py
    - rm rsm.yaml
