language: python
python:
    - 2.6
    - 2.7
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install importlib; fi
    - pip install -r requirements.txt
script:
    nosetests
