language: python
python:
    - 2.6
    - 2.7
addons:
  postgresql: "9.3"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install importlib; fi
    - pip install -r requirements.txt
    - pip install coveralls
before_script:
  - psql -c 'create database rsm_test;' -U postgres
script:
    nosetests --with-coverage --cover-package=raw_sql_migrate
after_success:
  - coveralls
